### PR TITLE
Update RibbonApi 1.1 for Word and PowerPoint on Windows and Mac

### PR DESCRIPTION
**Pull request by yjz2021**
Updated RibbonApi1.1 support information for Word and PowerPoint on Windows and Mac.

### CODE REVIEW

**Comment by yjz2021** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by yjz2021** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by yjz2021** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by gergzk — COMMENTED** [review]
This is enabling Word+PPT for Mac+Win32

**Review by cproscia — APPROVED** [review]

**Pull request merged**
